// <auto-generated />
using Backend;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Backend.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20201202120709_imagem")]
    partial class imagem
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Backend.Modelo.Produto", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("nome")
                        .HasColumnType("text");

                    b.Property<decimal>("peso")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("preco")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("urlImagem")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("PRODUTO");
                });
#pragma warning restore 612, 618
        }
    }
}
