// <auto-generated />
using Backend;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Backend.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Backend.Modelo.Comentario", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("comentario")
                        .HasColumnType("text");

                    b.Property<long>("produtoId")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("produtoId");

                    b.ToTable("COMENTARIOS");
                });

            modelBuilder.Entity("Backend.Modelo.Produto", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("nome")
                        .HasColumnType("text");

                    b.Property<decimal>("peso")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("preco")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("urlImagem")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("PRODUTO");
                });

            modelBuilder.Entity("Backend.Modelo.Comentario", b =>
                {
                    b.HasOne("Backend.Modelo.Produto", "produto")
                        .WithMany()
                        .HasForeignKey("produtoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
